name: Release

# trigger release build when a version tag is pushed
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # only continue if the tag was pushed to `main`
      - name: Main branch?
        run: |
          TAG_COMMIT=$(git rev-parse "$GITHUB_REF")
          git fetch origin main
          if git merge-base --is-ancestor "$TAG_COMMIT" origin/main; then
            echo "Tag is on main branch ⇝ release "
          else
            echo "Tag is NOT on main branch ⇝ exit"
            exit 1
          fi
      - name: Determine version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "Releasing version ${GITHUB_REF#refs/tags/v}"
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      - name: Run release build
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_TOKEN_NAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASS }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.PGP_PASS }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.PGP_PUBLIC }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.PGP_SECRET }}
        run: mvn -P release -D revision=${{ env.VERSION }} deploy --no-transfer-progress
