name: Release

# release builds are manually dispatched
on:
  workflow_dispatch:
    inputs:
      releasing:
        description: "Is this a release build?"
        type: boolean
        default: false
        required: true
      version:
        description: 'Version string, e.g. 0.4.2'
        required: true

jobs:
  release:
    if: github.event.inputs.releasing && github.event.inputs.version != ''
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      - name: Run release build
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.NEXUS_TOKEN_NAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.NEXUS_TOKEN_PASS }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.PGP_PASS }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.PGP_PUBLIC }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.PGP_SECRET }}
        run: mvn -P release -D revision=${{ github.event.inputs.version }} deploy --no-transfer-progress
